language: go

go:
  - 1.8.x

before_install:
  - go get -u github.com/kardianos/govendor
  - govendor sync

script:
  - go test github.com/sanksons/reflorest/src/common/collections/maps/concurrentmap/concurrenthashmap